export declare enum AdvAdapterEvent {
    INTERSTITIAL_ADV_SHOW = "AdvAdapterEvent.INTERSTITIAL_ADV_SHOW",
    INTERSTITIAL_ADV_SUCCESS = "AdvAdapterEvent.INTERSTITIAL_ADV_SUCCESS",
    INTERSTITIAL_ADV_ERROR = "AdvAdapterEvent.INTERSTITIAL_ADV_ERROR",
    REWARDED_ADV_SHOW = "AdvAdapterEvent.REWARDED_ADV_SHOW",
    REWARDED_ADV_SUCCESS = "AdvAdapterEvent.REWARDED_ADV_SUCCESS",
    REWARDED_ADV_ERROR = "AdvAdapterEvent.REWARDED_ADV_ERROR",
    BANNER_ADV_SHOW = "AdvAdapterEvent.BANNER_ADV_SHOW",
    BANNER_ADV_SUCCESS = "AdvAdapterEvent.BANNER_ADV_SUCCESS",
    BANNER_ADV_ERROR = "AdvAdapterEvent.BANNER_ADV_ERROR"
}
